import type { Pool, PoolConnection } from "mysql2/promise";
import { mapExpeditionToCourier } from "@/lib/shipping/courier-map";
import { createMockShipment } from "@/lib/shipping/mock-shipment";
import { loadShipmentContext } from "@/lib/shipping/shipment-context";
import { canAutoCreateShipment } from "@/lib/shipping/shipping-provider";

type Queryable = Pool | PoolConnection;

export type MarkShippedInput = {
  idPengiriman: number;
  idAdmin: number;
  nomorResi?: string;
  autoGenerate?: boolean;
  courierType?: string;
};

export type MarkShippedResult = {
  nomorResi: string;
  autoGenerated: boolean;
  courierCompany: string | null;
  message: string;
};

export async function markShipmentAsShipped(
  input: MarkShippedInput,
  db: Queryable
): Promise<MarkShippedResult> {
  const ctx = await loadShipmentContext(input.idPengiriman, db);
  if (!ctx) {
    throw new Error("Shipment not found or invoice is not paid.");
  }
  if (ctx.status_pengiriman !== "diproses") {
    throw new Error("Shipment is not in processing status.");
  }

  const manualResi = (input.nomorResi ?? "").trim();
  const expedition = (ctx.ekspedisi ?? "").trim();

  let nomorResi = manualResi;
  let autoGenerated = false;
  let courierCompany: string | null = null;

  if (!nomorResi) {
    const shouldAutoShip = input.autoGenerate !== false && canAutoCreateShipment();
    if (!shouldAutoShip) {
      throw new Error("Enter a tracking number or leave empty to generate a mock AWB.");
    }
    if (!expedition) {
      throw new Error("Courier is missing on this order. Set expedition on the quotation first.");
    }

    const created = await createMockShipment({
      idInvoice: ctx.id_invoice,
      invoiceNumber: ctx.nomor_invoice,
      expedition,
      courierType: input.courierType,
    });

    nomorResi = created.waybillId;
    autoGenerated = true;
    courierCompany = created.courierCompany;
  } else if (nomorResi.length > 100) {
    throw new Error("Tracking number must be at most 100 characters.");
  } else if (expedition) {
    const mapped = mapExpeditionToCourier(expedition, input.courierType);
    if (mapped) {
      courierCompany = mapped.company;
    }
  }

  const [upd] = await db.query(
    `UPDATE pengiriman
     SET status_pengiriman = 'dikirim',
         nomor_resi = ?,
         tanggal_pengiriman = NOW(),
         id_admin = ?
     WHERE id_pengiriman = ?
       AND status_pengiriman = 'diproses'`,
    [nomorResi, input.idAdmin, input.idPengiriman]
  );

  if ((upd as { affectedRows: number }).affectedRows === 0) {
    throw new Error("Shipment could not be updated. It may have already been shipped.");
  }

  const message = autoGenerated
    ? `Shipped (mock). AWB: ${nomorResi}`
    : "Marked as shipped. The buyer can track and confirm delivery.";

  return {
    nomorResi,
    autoGenerated,
    courierCompany,
    message,
  };
}
